import Link from 'next/link';
import { BookOpen, Code2, Database, GitBranch, Scale } from 'lucide-react';
import DashboardShell from '@/components/dashboard-shell';
import { Panel } from '@/components/ui';

export default function DocumentationPage() {
  return <DashboardShell title="Documentation" subtitle="A short guide to the analytical methodology, data model and limitations behind this portfolio product.">
    <div className="grid gap-4 xl:grid-cols-2"><Panel title="Project purpose" eyebrow="Business context"><p className="text-sm leading-7 text-slate-300">Fraud Command Center demonstrates explainable transaction monitoring for a bank or fintech risk team. It combines chronological behavioral features, configurable rules, composite risk scoring, anomaly detection, model evaluation and investigation workflow.</p><p className="mt-4 text-xs leading-5 text-slate-500">The system supports analyst review. It does not automatically block customers and is not connected to a real financial institution.</p></Panel><Panel title="Synthetic data policy" eyebrow="Transparency"><p className="text-sm leading-7 text-slate-300">The generator creates anonymized customers, accounts, devices, beneficiaries and transactions with a fixed seed. The actual fraud rate, rule metrics and insights are recalculated whenever data is regenerated.</p><p className="mt-4 text-xs leading-5 text-amber-100/70">Never publish real customer data, card numbers, identity documents or bank account details in a portfolio repository.</p></Panel></div>
    <div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Panel title="Data model" eyebrow="Tables"><Database className="mb-4 text-blue-300" size={22} /><p className="text-xs leading-5 text-slate-400">Entity tables, transaction facts, leakage-safe features, rule results, alerts, score components and cases are separated for auditability.</p><Link href="/data-quality" className="mt-4 inline-block text-xs text-blue-300">View data quality →</Link></Panel><Panel title="Rule engine" eyebrow="Explainability"><Scale className="mb-4 text-amber-300" size={22} /><p className="text-xs leading-5 text-slate-400">R001–R012 are configured in YAML and persist each triggered reason separately.</p><Link href="/rules" className="mt-4 inline-block text-xs text-blue-300">View rule performance →</Link></Panel><Panel title="ML approach" eyebrow="Prioritization"><GitBranch className="mb-4 text-purple-300" size={22} /><p className="text-xs leading-5 text-slate-400">Logistic Regression and Isolation Forest are evaluated with a time split. PR-AUC is emphasized for the rare class.</p><Link href="/models" className="mt-4 inline-block text-xs text-blue-300">View model evaluation →</Link></Panel><Panel title="Developer docs" eyebrow="Local setup"><Code2 className="mb-4 text-emerald-300" size={22} /><p className="text-xs leading-5 text-slate-400">FastAPI exposes OpenAPI docs and the repository README documents the local pipeline and deployment path.</p><a href="http://localhost:8000/docs" target="_blank" rel="noreferrer" className="mt-4 inline-block text-xs text-blue-300">Open API docs →</a></Panel></div>
    <Panel className="mt-4" title="Ethical considerations" eyebrow="Limitations"><ul className="grid gap-3 md:grid-cols-2">{['Risk score is a prioritization signal, not proof of fraud.', 'Network relationships require investigator review.', 'Synthetic labels do not measure production fraud outcomes.', 'Geography, age and other sensitive attributes require fairness analysis.', 'Human review is required before customer-impacting actions.', 'Estimated prevented loss is a documented simulation assumption.'].map((item) => <li key={item} className="flex gap-2 text-sm text-slate-400"><BookOpen size={15} className="mt-0.5 shrink-0 text-blue-300" />{item}</li>)}</ul></Panel>
  </DashboardShell>;
}
