'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ArrowLeft, MapPin, Smartphone, Users } from 'lucide-react';
import DashboardShell from '@/components/dashboard-shell';
import { apiFetch } from '@/lib/api';
import { Badge, Button, ErrorState, LoadingState, MetricCard, Panel, formatDate, formatMoney, formatNumber } from '@/components/ui';
import { BarMetricChart, TrendChart } from '@/components/charts';

type CustomerDetail = { profile: Record<string, any>; stats: Record<string, any>; recent_transactions: Record<string, any>[]; alerts: Record<string, any>[]; devices: Record<string, any>[]; countries: Record<string, any>[]; cities: Record<string, any>[]; top_beneficiaries: Record<string, any>[]; activity_timeline: Record<string, any>[] };

export default function CustomerDetailPage() {
  const params = useParams<{ customerId: string }>();
  const [data, setData] = useState<CustomerDetail | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { if (params.customerId) apiFetch<CustomerDetail>(`/api/customers/${params.customerId}`).then(setData).catch((reason) => setError(reason.message)); }, [params.customerId]);
  if (error) return <DashboardShell title="Customer 360"><ErrorState message={error} /></DashboardShell>;
  if (!data) return <DashboardShell title="Customer 360"><LoadingState /></DashboardShell>;
  const profile = data.profile;
  return <DashboardShell title={`${profile.customer_id} · Customer 360`} subtitle="A single-screen view of profile risk, money movement, devices, geography, beneficiaries and alerts." actions={<Button href="/customers"><ArrowLeft size={14} />Back to customers</Button>}>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Profile risk" value={<Badge tone={String(profile.customer_risk_level)}>{String(profile.customer_risk_level)}</Badge>} detail={String(profile.customer_type)} icon={<Users size={16} />} /><MetricCard label="Transactions" value={formatNumber(data.stats.transaction_count)} detail="Observed in generated period" icon={<MapPin size={16} />} /><MetricCard label="Total volume" value={formatMoney(data.stats.total_volume)} detail="Synthetic transaction amount" /><MetricCard label="Alerts" value={formatNumber(data.stats.alert_count)} detail="Prioritized alerts" tone="amber" /><MetricCard label="Fraud-label count" value={formatNumber(data.stats.confirmed_fraud_count)} detail="Synthetic ground truth only" tone="red" /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[0.8fr_1.2fr]"><Panel title="Profile" eyebrow="Customer identity"><div className="grid gap-4 sm:grid-cols-2"><div><p className="text-xs text-slate-500">Name</p><p className="mt-1 text-lg font-semibold text-white">{String(profile.anonymized_name)}</p></div><div><p className="text-xs text-slate-500">Registration</p><p className="mt-1 text-slate-200">{formatDate(profile.registration_date)}</p></div><div><p className="text-xs text-slate-500">Region / city</p><p className="mt-1 text-slate-200">{String(profile.region)} · {String(profile.city)}</p></div><div><p className="text-xs text-slate-500">Occupation</p><p className="mt-1 text-slate-200">{String(profile.occupation)}</p></div><div><p className="text-xs text-slate-500">Monthly income</p><p className="mt-1 text-slate-200">{formatMoney(profile.monthly_income)}</p></div><div><p className="text-xs text-slate-500">Verification</p><p className="mt-1">{profile.is_verified ? <Badge tone="green">Verified</Badge> : <Badge>Unverified</Badge>}</p></div></div></Panel><Panel title="Activity timeline" eyebrow="Behavior over time"><TrendChart data={data.activity_timeline} dataKey="transaction_count" secondaryKey="total_amount" /></Panel></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><Panel title="Devices" eyebrow={`${data.devices.length} linked devices`}><div className="space-y-2">{data.devices.map((device) => <Link key={String(device.device_id)} href={`/network?entity=${device.device_id}`} className="flex items-center justify-between rounded-md border border-line p-3 text-xs hover:bg-slate-900/60"><span className="flex items-center gap-2 text-slate-200"><Smartphone size={14} className="text-blue-300" />{String(device.device_id)}</span><span className="text-slate-500">risk {formatNumber(device.device_risk_score, 1)}</span></Link>)}</div></Panel><Panel title="Countries and cities" eyebrow="Geographic footprint"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><div><p className="mb-2 text-xs text-slate-500">Countries</p><BarMetricChart data={data.countries} nameKey="country" dataKey="transactions" height={150} /></div><div><p className="mb-2 text-xs text-slate-500">Cities</p><BarMetricChart data={data.cities} nameKey="city" dataKey="transactions" height={150} color="#34d399" /></div></div></Panel><Panel title="Top beneficiaries" eyebrow="Destination concentration"><div className="space-y-3">{data.top_beneficiaries.map((beneficiary) => <div key={String(beneficiary.beneficiary_id)} className="flex items-center justify-between border-b border-line/70 pb-2 text-xs"><Link href={`/network?entity=${beneficiary.beneficiary_id}`} className="text-blue-300">{String(beneficiary.beneficiary_id)}</Link><span className="text-slate-400">{formatMoney(beneficiary.total_amount)} · {formatNumber(beneficiary.transaction_count)} tx</span></div>)}</div></Panel></div>
    <Panel className="mt-4" title="Recent transactions" eyebrow="Customer activity"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-xs"><thead className="border-b border-line text-[10px] uppercase text-slate-500"><tr><th className="py-2">Time</th><th className="py-2">Transaction</th><th className="py-2">Amount</th><th className="py-2">Channel</th><th className="py-2">Location</th><th className="py-2">Label</th></tr></thead><tbody>{data.recent_transactions.map((item) => <tr key={String(item.transaction_id)} className="border-b border-line/60"><td className="py-2 text-slate-500">{formatDate(item.timestamp)}</td><td className="py-2"><Link className="text-blue-300" href={`/transactions/${item.transaction_id}`}>{String(item.transaction_id)}</Link></td><td className="py-2 text-white">{formatMoney(item.amount, String(item.currency || 'USD'))}</td><td className="py-2 text-slate-400">{String(item.channel)}</td><td className="py-2 text-slate-400">{String(item.city)}</td><td className="py-2">{item.is_fraud ? <Badge tone="red">Fraud label</Badge> : <Badge tone="green">Normal</Badge>}</td></tr>)}</tbody></table></div></Panel>
  </DashboardShell>;
}
