'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ArrowLeft, Clock3, Network, WalletCards } from 'lucide-react';
import DashboardShell from '@/components/dashboard-shell';
import { apiFetch } from '@/lib/api';
import { Badge, Button, ErrorState, LoadingState, Panel, formatDate, formatMoney, formatNumber } from '@/components/ui';

type TransactionDetail = { transaction: Record<string, any>; features: Record<string, any>[]; alerts: Record<string, any>[]; triggered_rules: Record<string, any>[]; recent_customer_transactions: Record<string, any>[]; device: Record<string, any>[]; beneficiary: Record<string, any>[] };

export default function TransactionDetailPage() {
  const params = useParams<{ transactionId: string }>();
  const [data, setData] = useState<TransactionDetail | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { if (params.transactionId) apiFetch<TransactionDetail>(`/api/transactions/${params.transactionId}`).then(setData).catch((reason) => setError(reason.message)); }, [params.transactionId]);
  if (error) return <DashboardShell title="Transaction detail"><ErrorState message={error} /></DashboardShell>;
  if (!data) return <DashboardShell title="Transaction detail"><LoadingState /></DashboardShell>;
  const transaction = data.transaction;
  const feature = data.features[0] || {};
  return <DashboardShell title={`${transaction.transaction_id} · Transaction detail`} subtitle="An auditable event view with balance movement, customer baseline, rules and related entities." actions={<Button href="/transactions"><ArrowLeft size={14} />Back to explorer</Button>}>
    <div className="grid gap-4 xl:grid-cols-3"><Panel title="Event summary" eyebrow="Transaction timeline" className="xl:col-span-2"><div className="grid gap-5 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Timestamp</p><p className="mt-1 text-sm text-white">{formatDate(transaction.timestamp)}</p></div><div><p className="text-xs text-slate-500">Amount</p><p className="mt-1 text-2xl font-semibold text-white">{formatMoney(transaction.amount, transaction.currency)}</p></div><div><p className="text-xs text-slate-500">Status</p><p className="mt-1"><Badge tone={transaction.status === 'completed' ? 'green' : 'amber'}>{String(transaction.status)}</Badge></p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-lg border border-line bg-slate-900/40 p-4"><p className="text-xs text-slate-500">Balance before</p><p className="mt-2 text-lg font-semibold text-white">{formatMoney(transaction.balance_before, transaction.currency)}</p></div><div className="rounded-lg border border-line bg-slate-900/40 p-4"><p className="text-xs text-slate-500">Balance after</p><p className="mt-2 text-lg font-semibold text-white">{formatMoney(transaction.balance_after, transaction.currency)}</p></div></div></Panel><Panel title="Risk context" eyebrow="Synthetic label"><div className="flex h-full flex-col justify-between gap-5"><div>{transaction.is_fraud ? <Badge tone="red">Synthetic fraud label</Badge> : <Badge tone="green">Normal label</Badge>}<p className="mt-3 text-sm leading-6 text-slate-400">Scenario: <span className="text-slate-200">{String(transaction.fraud_scenario)}</span></p></div><div className="rounded-lg border border-amber-400/20 bg-amber-400/5 p-3 text-xs leading-5 text-amber-100/80">The label is available for evaluation only. It is not an input to monitoring features.</div></div></Panel></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><Panel title="Customer baseline" eyebrow="Prior behavior"><div className="grid grid-cols-2 gap-4 text-sm"><div><p className="text-xs text-slate-500">Prior average amount</p><p className="mt-1 text-white">{formatMoney(feature.customer_avg_transaction_amount, transaction.currency)}</p></div><div><p className="text-xs text-slate-500">Amount vs average</p><p className="mt-1 text-white">{formatNumber(feature.amount_vs_customer_average, 2)}x</p></div><div><p className="text-xs text-slate-500">1-hour velocity</p><p className="mt-1 text-white">{formatNumber(feature.transactions_last_1_hour)}</p></div><div><p className="text-xs text-slate-500">New beneficiary</p><p className="mt-1 text-white">{feature.is_new_beneficiary ? 'Yes' : 'No'}</p></div></div></Panel><Panel title="Triggered rules" eyebrow="Explainable controls"><div className="space-y-2">{data.triggered_rules.length ? data.triggered_rules.map((rule) => <div key={String(rule.rule_result_id)} className="rounded-md border border-line p-3"><div className="flex justify-between"><span className="text-xs font-semibold text-white">{String(rule.rule_id)} · {String(rule.rule_name)}</span><span className="text-xs text-amber-200">+{formatNumber(rule.rule_score)}</span></div><p className="mt-1 text-xs text-slate-500">{String(rule.rule_reason)}</p></div>) : <p className="text-sm text-slate-500">No triggered rules.</p>}</div></Panel><Panel title="Related entities" eyebrow="Context"><div className="space-y-4 text-sm"><div><p className="text-xs text-slate-500">Customer</p><Link className="text-blue-300" href={`/customers/${transaction.sender_customer_id}`}>{String(transaction.sender_customer_id)}</Link></div><div><p className="text-xs text-slate-500">Device</p><Link className="text-blue-300" href={`/network?entity=${transaction.device_id}`}>{String(transaction.device_id)}</Link></div><div><p className="text-xs text-slate-500">Beneficiary</p><Link className="text-blue-300" href={`/network?entity=${transaction.beneficiary_id}`}>{String(transaction.beneficiary_id)}</Link></div><div className="flex items-center gap-2 text-xs text-slate-500"><Network size={14} />Network signals require investigator review.</div></div></Panel></div>
    <Panel className="mt-4" title="Recent customer transactions" eyebrow="Behavioral timeline"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="border-b border-line text-[10px] uppercase text-slate-500"><tr><th className="py-2">Time</th><th className="py-2">Transaction</th><th className="py-2">Amount</th><th className="py-2">Channel</th><th className="py-2">City</th><th className="py-2">Label</th></tr></thead><tbody>{data.recent_customer_transactions.map((item) => <tr key={String(item.transaction_id)} className="border-b border-line/60"><td className="py-2 text-slate-500">{formatDate(item.timestamp)}</td><td className="py-2"><Link className="text-blue-300" href={`/transactions/${item.transaction_id}`}>{String(item.transaction_id)}</Link></td><td className="py-2 text-white">{formatMoney(item.amount, String(item.currency || 'USD'))}</td><td className="py-2 text-slate-400">{String(item.channel)}</td><td className="py-2 text-slate-400">{String(item.city)}</td><td className="py-2">{item.is_fraud ? <Badge tone="red">Fraud</Badge> : <Badge tone="green">Normal</Badge>}</td></tr>)}</tbody></table></div></Panel>
    <div className="mt-4 flex items-center gap-2 text-xs text-slate-500"><Clock3 size={14} />All behavioral features are calculated from information available before the current event.</div>
  </DashboardShell>;
}
