'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowUpRight, CheckCircle2, FilePlus2, MessageSquare, ShieldAlert } from 'lucide-react';
import DashboardShell from '@/components/dashboard-shell';
import { apiFetch } from '@/lib/api';
import { Badge, Button, ErrorState, LoadingState, Panel, formatDate, formatMoney, formatNumber } from '@/components/ui';
import { BarMetricChart } from '@/components/charts';

type AlertDetail = { alert: Record<string, any>; transaction: Record<string, any>; customer: Record<string, any>; features: Record<string, any>; triggered_rules: Record<string, any>[]; score_components: Record<string, any>[]; timeline: Record<string, any>[]; device: Record<string, any>; beneficiary: Record<string, any>; related_accounts: Record<string, any>[]; similar_alerts: Record<string, any>[]; recommendation: string; why_flagged: string };

export default function AlertDetailPage() {
  const params = useParams<{ alertId: string }>();
  const [data, setData] = useState<AlertDetail | null>(null);
  const [error, setError] = useState('');
  const [note, setNote] = useState('');
  const load = () => apiFetch<AlertDetail>(`/api/alerts/${params.alertId}`).then((payload) => { setData(payload); setNote(String(payload.alert.investigation_notes || '')); }).catch((reason) => setError(reason.message));
  useEffect(() => { if (params.alertId) load(); }, [params.alertId]);
  async function update(status: string) { await apiFetch(`/api/alerts/${params.alertId}`, { method: 'PATCH', body: JSON.stringify({ alert_status: status, disposition: status === 'Confirmed Fraud' || status === 'False Positive' ? status : undefined, investigation_notes: note || undefined }) }); load(); }
  async function createCase() { await apiFetch('/api/cases', { method: 'POST', body: JSON.stringify({ alert_id: params.alertId, priority: data?.alert.alert_priority || 'P2', analyst_comment: note || null }) }); alert('Investigation case created.'); }
  if (error) return <DashboardShell title="Alert detail"><ErrorState message={error} /></DashboardShell>;
  if (!data) return <DashboardShell title="Alert detail"><LoadingState /></DashboardShell>;
  const scoreComponents = data.score_components.map((component) => ({ name: String(component.component_name), contribution: Number(component.weighted_contribution || 0) }));
  return <DashboardShell title={`${data.alert.alert_id} · Alert detail`} subtitle="Review the explainable score, transaction context and connected entities before choosing a workflow action." actions={<Button href="/alerts"><ArrowLeft size={14} />Back to queue</Button>}>
    <div className="grid gap-4 xl:grid-cols-[1.4fr_0.6fr]">
      <Panel title="Why was this flagged?" eyebrow="Explainability"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><p className="max-w-3xl text-sm leading-7 text-slate-300">{data.why_flagged}</p><div className="rounded-xl border border-red-400/20 bg-red-400/5 px-6 py-4 text-center"><p className="text-[10px] uppercase tracking-wide text-red-200/70">Risk score</p><p className="mt-1 text-4xl font-semibold text-white">{formatNumber(data.alert.risk_score, 1)}</p><Badge tone={String(data.alert.risk_level)}>{String(data.alert.risk_level)}</Badge></div></div><div className="mt-4 rounded-lg border border-amber-400/20 bg-amber-400/5 p-3 text-xs leading-5 text-amber-100/80">Recommendation: {data.recommendation}. This is an analytical support signal; human review is required.</div></Panel>
      <Panel title="Workflow" eyebrow="Analyst actions"><div className="space-y-3"><p className="text-xs text-slate-500">Current status</p><Badge tone={String(data.alert.alert_status)}>{String(data.alert.alert_status)}</Badge><div className="grid gap-2 pt-2"><Button variant="danger" onClick={() => update('Confirmed Fraud')}><ShieldAlert size={14} />Mark as fraud</Button><Button onClick={() => update('False Positive')}><CheckCircle2 size={14} />Mark as false positive</Button><Button onClick={() => update('Escalated')}><ArrowUpRight size={14} />Escalate</Button><Button onClick={createCase}><FilePlus2 size={14} />Create investigation case</Button><Button variant="secondary" onClick={() => update('Closed')}>Close alert</Button></div><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Investigation note" className="mt-2 min-h-24 w-full rounded-md border border-line bg-slate-900 p-3 text-xs text-slate-200 outline-none" /><Button onClick={() => update(String(data.alert.alert_status))}><MessageSquare size={14} />Save note</Button></div></Panel>
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Score contribution breakdown" eyebrow="Weighted components"><BarMetricChart data={scoreComponents} nameKey="name" dataKey="contribution" color="#60a5fa" /></Panel><Panel title="Transaction context" eyebrow="Event facts"><div className="grid gap-4 sm:grid-cols-2">{[['Transaction', data.transaction.transaction_id], ['Timestamp', formatDate(data.transaction.timestamp)], ['Amount', formatMoney(data.transaction.amount, data.transaction.currency)], ['Channel', data.transaction.channel], ['Location', `${data.transaction.city}, ${data.transaction.country}`], ['Balance after', formatMoney(data.transaction.balance_after, data.transaction.currency)], ['Device', data.transaction.device_id], ['Beneficiary', data.transaction.beneficiary_id]].map(([label, value]) => <div key={String(label)}><p className="text-[10px] uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-sm text-slate-200">{String(value || '—')}</p></div>)}</div></Panel></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><Panel title="Triggered rules" eyebrow="Rule evidence"><div className="space-y-3">{data.triggered_rules.length ? data.triggered_rules.map((rule) => <div key={String(rule.rule_result_id)} className="rounded-lg border border-line bg-slate-900/50 p-3"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-white">{String(rule.rule_id)} · {String(rule.rule_name)}</span><Badge tone="high">+{formatNumber(rule.rule_score, 0)}</Badge></div><p className="mt-2 text-xs leading-5 text-slate-400">{String(rule.rule_reason)}</p></div>) : <p className="text-sm text-slate-500">No individual rule evidence persisted.</p>}</div></Panel><Panel title="Customer profile" eyebrow="Customer 360"><div className="space-y-3 text-sm"><Link href={`/customers/${data.customer.customer_id}`} className="text-lg font-semibold text-blue-300">{String(data.customer.customer_id)}</Link><p className="text-slate-400">{String(data.customer.anonymized_name)}</p><div className="flex items-center gap-2"><Badge tone={String(data.customer.customer_risk_level)}>{String(data.customer.customer_risk_level)} profile risk</Badge><span className="text-xs text-slate-500">{String(data.customer.customer_type)}</span></div><div className="grid grid-cols-2 gap-3 pt-2"><div><p className="text-xs text-slate-500">Age</p><p>{String(data.customer.age)}</p></div><div><p className="text-xs text-slate-500">Region</p><p>{String(data.customer.region)}</p></div></div></div></Panel><Panel title="Device and beneficiary" eyebrow="Related entities"><div className="space-y-4 text-xs"><div><p className="text-slate-500">Device</p><p className="mt-1 text-slate-200">{String(data.device.device_id)} · {String(data.device.device_type)}</p><p className="mt-1 text-slate-500">{String(data.device.country)}, {String(data.device.city)} · risk {formatNumber(data.device.device_risk_score, 1)}</p></div><div><p className="text-slate-500">Beneficiary</p><p className="mt-1 text-slate-200">{String(data.beneficiary.beneficiary_id)} · {String(data.beneficiary.category)}</p><p className="mt-1 text-slate-500">{String(data.beneficiary.country)} · {String(data.beneficiary.beneficiary_risk_level)} risk</p></div><Link href={`/network?entity=${data.device.device_id}`} className="inline-block text-blue-300">Open network context →</Link></div></Panel></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Customer transaction timeline" eyebrow="Recent activity"><div className="max-h-72 overflow-auto"><table className="w-full text-left text-xs"><thead className="border-b border-line text-[10px] uppercase text-slate-500"><tr><th className="py-2">Timestamp</th><th className="py-2">Transaction</th><th className="py-2">Amount</th><th className="py-2">City</th></tr></thead><tbody>{data.timeline.map((transaction) => <tr key={String(transaction.transaction_id)} className="border-b border-line/60"><td className="py-2 text-slate-500">{formatDate(transaction.timestamp)}</td><td className="py-2"><Link className="text-blue-300" href={`/transactions/${transaction.transaction_id}`}>{String(transaction.transaction_id)}</Link></td><td className="py-2 text-slate-200">{formatMoney(transaction.amount, String(transaction.currency || 'USD'))}</td><td className="py-2 text-slate-400">{String(transaction.city)}</td></tr>)}</tbody></table></div></Panel><Panel title="Analyst notes" eyebrow="Human review"><div className="flex items-start gap-3 text-sm leading-6 text-slate-400"><MessageSquare size={17} className="mt-1 text-blue-300" />Notes are saved through the alert PATCH endpoint and should reference evidence, customer contact and the final rationale.</div></Panel></div>
  </DashboardShell>;
}
