'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowRight, Gauge, Settings2 } from 'lucide-react';
import DashboardShell from '@/components/dashboard-shell';
import { apiFetch } from '@/lib/api';
import { Badge, Button, ErrorState, LoadingState, Panel, formatMoney, formatNumber } from '@/components/ui';

type RuleResponse = { definitions: Record<string, any>[]; performance: { rules: Record<string, any>[]; versions: Record<string, any>[]; pareto: Record<string, any>[] } };

export default function RulesPage() {
  const [data, setData] = useState<RuleResponse | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { apiFetch<RuleResponse>('/api/rules').then(setData).catch((reason) => setError(reason.message)); }, []);
  if (error) return <DashboardShell title="Rule Performance"><ErrorState message={error} /></DashboardShell>;
  if (!data) return <DashboardShell title="Rule Performance"><LoadingState /></DashboardShell>;
  return <DashboardShell title="Rule Performance" subtitle="Rule-level alert volume, synthetic precision, recall, false positives and analyst workload. Recommendations are analytical, not final business decisions." actions={<Button href="/rules/tuning"><Settings2 size={14} />Open rule tuning</Button>}>
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-blue-400/20 bg-blue-400/5 p-4"><p className="text-xs text-slate-500">Configured rules</p><p className="mt-2 text-2xl font-semibold text-white">{formatNumber(data.definitions.length)}</p></div><div className="rounded-xl border border-line bg-panel p-4"><p className="text-xs text-slate-500">V2 triggered rows</p><p className="mt-2 text-2xl font-semibold text-white">{formatNumber(data.performance.rules.reduce((sum, rule) => sum + Number(rule.alerts_generated || 0), 0))}</p></div><div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-4"><p className="text-xs text-slate-500">Rules to investigate</p><p className="mt-2 text-2xl font-semibold text-white">{formatNumber(data.performance.rules.filter((rule) => rule.recommendation !== 'keep').length)}</p></div></div>
    <Panel className="mt-4" title="Rule scorecard" eyebrow="V2 current configuration"><div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-left text-xs"><thead className="border-b border-line text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Rule</th><th className="px-3 py-3">Category</th><th className="px-3 py-3">Alerts</th><th className="px-3 py-3">Confirmed fraud</th><th className="px-3 py-3">False positives</th><th className="px-3 py-3">Precision</th><th className="px-3 py-3">Recall</th><th className="px-3 py-3">Analyst min</th><th className="px-3 py-3">Recommendation</th></tr></thead><tbody>{data.performance.rules.map((rule) => <tr key={`${rule.version}-${rule.rule_id}`} className="border-b border-line/70"><td className="px-3 py-3"><p className="font-semibold text-white">{String(rule.rule_id)} · {String(rule.rule_name)}</p><p className="mt-1 max-w-[280px] text-[10px] leading-4 text-slate-500">{String(rule.description)}</p></td><td className="px-3 py-3 text-slate-400">{String(rule.category)}</td><td className="px-3 py-3 text-white">{formatNumber(rule.alerts_generated)}</td><td className="px-3 py-3 text-emerald-200">{formatNumber(rule.confirmed_fraud)}</td><td className="px-3 py-3 text-red-200">{formatNumber(rule.false_positives)}</td><td className="px-3 py-3">{formatNumber(Number(rule.precision) * 100, 1)}%</td><td className="px-3 py-3">{formatNumber(Number(rule.recall) * 100, 1)}%</td><td className="px-3 py-3 text-slate-400">{formatNumber(rule.estimated_analyst_minutes)}</td><td className="px-3 py-3"><Badge tone={String(rule.recommendation)}>{String(rule.recommendation)}</Badge></td></tr>)}</tbody></table></div></Panel>
    <Panel className="mt-4" title="Version comparison" eyebrow="V1 broad rules vs V2 contextual rules"><div className="grid gap-3 md:grid-cols-2">{data.performance.rules.map((rule) => <div key={`compare-${rule.rule_id}`} className="rounded-lg border border-line bg-slate-900/40 p-3"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-white">{String(rule.rule_id)} · {String(rule.rule_name)}</span><span className="text-[10px] text-slate-500">V1 → V2</span></div><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><p className="text-slate-500">Alert volume</p><p className="mt-1 text-slate-200">{formatNumber(rule.v1_alerts)} → {formatNumber(rule.v2_alerts)}</p></div><div><p className="text-slate-500">Precision</p><p className="mt-1 text-slate-200">{formatNumber(Number(rule.v1_precision) * 100, 1)}% → {formatNumber(Number(rule.v2_precision) * 100, 1)}%</p></div></div></div>)}</div></Panel>
    <div className="mt-4 flex items-center gap-2 text-xs text-slate-500"><Gauge size={14} />Use the tuning simulator to test thresholds without changing the stored configuration.<Link href="/rules/tuning" className="inline-flex items-center gap-1 text-blue-300">Tune rules <ArrowRight size={13} /></Link></div>
  </DashboardShell>;
}
